steps:
  # Step 1: Build the Docker image for the Flask app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile', '-t', 'gcr.io/$PROJECT_ID/portfolio_flask-app', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/portfolio_flask-app']

  # Optional Deployment Step (if you plan to deploy the app)
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['run', 'gcr.io/$PROJECT_ID/portfolio_flask-app']

# Logging and Options
logsBucket: gs://my-build-logs-bucket  # Replace with your actual logs bucket name
options:
  logging: CLOUD_LOGGING_ONLY  # Logs will be sent only to Google Cloud Logging
  # Uncomment if you want to use a regional user-owned bucket
  # defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

# Substitutions (optional)
substitutions:
  _FLASK_APP_IMAGE: 'gcr.io/$PROJECT_ID/portfolio_flask-app'

# Specify the images to be stored in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/portfolio_flask-app'



# powershell -ExecutionPolicy Bypass -Command "gcloud builds submit --config cloudbuild.yaml ."
# gcloud builds submit --tag gcr.io/portfolio-428612/portfolio_flask-app
# gcloud run deploy portfolio-flask-app --image gcr.io/portfolio-428612/portfolio_flask-app --platform managed

